=== radverg/radverg.github.io/cv_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="CV">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="PersonalInfo" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="FirstName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="LastName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Email" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Phone" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Address" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="LinkedIn" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="GitHub" type="xs:string" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Education" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Degree" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Institution" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Year" type="xs:gYear" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="WorkExperience" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Position" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="Company" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="StartDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="EndDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="Description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Skills" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Skill" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Languages" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Language" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Proficiency" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Project" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Description" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Link" type="xs:string" minOccurs="0" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Certifications" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Certification" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Title" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Institution" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="Year" type="xs:gYear" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== radverg/radverg.github.io/cv/cv_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cv.xslt"?>

<CV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cv_schema.xsd" 
    lang="en">
    <PersonalInfo title="Osobní informace">
        <FirstName title="Jméno">Radek</FirstName>
        <LastName title="Příjmení">Veverka</LastName>
        <Email title="Email">radek.veverka@icloud.com</Email>
        <Phone title="Telefon">777 996 598</Phone>
        <Address title="Adresa">Maršov 163, Veverská Bítýška 664 71</Address>
        <LinkedIn>
            <Caption>radek-veverka-62a88b1b1</Caption>
            <Href>https://www.linkedin.com/in/radek-veverka-62a88b1b1/</Href>
        </LinkedIn>
        <GitHub>
            <Caption>radverg</Caption>
            <Href>https://github.com/radverg</Href>
        </GitHub>
        
        <BioCaption>SW vývojář se zaměřením na web a .NET</BioCaption>
        <Portrait>portrait.jpg</Portrait>
        <Birth>
            <Date>3.1.1999</Date>
            <Place>Brno</Place>
            <Age>25</Age>
        </Birth>
    </PersonalInfo>
    
    <Education>
        <Degree>Bachelor of Science in Computer Science</Degree>
        <Institution>Some University</Institution>
        <Year>2018</Year>
    </Education>
    <Education>
        <Degree>Master of Science in Computer Science</Degree>
        <Institution>Some University</Institution>
        <Year>2020</Year>
    </Education>
    <WorkExperience>
        <Position>Software Engineer</Position>
        <Company>Tech Solutions</Company>
        <StartDate>2020-06-01</StartDate>
        <EndDate>2022-05-31</EndDate>
        <Description>Developed and maintained web applications using JavaScript, HTML, and CSS.</Description>
    </WorkExperience>
    <WorkExperience>
        <Position>Senior Software Engineer</Position>
        <Company>Innovative Apps</Company>
        <StartDate>2022-06-01</StartDate>
        <Description>Leading a team of developers in creating innovative software solutions.</Description>
    </WorkExperience>
    <Skills>
        <Skill>JavaScript</Skill>
        <Skill>HTML</Skill>
        <Skill>CSS</Skill>
        <Skill>React</Skill>
        <Skill>Node.js</Skill>
    </Skills>
    <Languages>
        <Language>
            <Name>English</Name>
            <Proficiency>Fluent</Proficiency>
        </Language>
        <Language>
            <Name>Spanish</Name>
            <Proficiency>Intermediate</Proficiency>
        </Language>
    </Languages>
    <Projects>
        <Project>
            <Title>Personal Portfolio Website</Title>
            <Description>Designed and developed a personal portfolio website to showcase my projects and skills.</Description>
            <Link>https://johndoe.dev</Link>
        </Project>
    </Projects>
    <Certifications>
        <Certification>
            <Title>Certified JavaScript Developer</Title>
            <Institution>Tech Institute</Institution>
            <Year>2019</Year>
        </Certification>
    </Certifications>
</CV>
